config/routes.rb
TheExplorerApis::Application.routes.draw do

  namespace :api do
    namespace :v1 do
      resource :user, :controller => 'user' , :only => [] do
        collection do
          post :signup
          get :login
          get :logout
          post :purchase
          get :user_detail
          put :reset_password
        end
      end
      resources :deal, :controller => 'deal'
      resources :merchant, :controller => 'merchant'
    end
  end
  root :to => "merchants#index"

  resources :merchants
  resources :deals
  resources :addresses
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  self.table_name = 'merchants'

  attr_accessible :email_address, :name, :address_id, :expire_at, :merchant_type, :uuid

  has_many :deals, :class_name => "Deal"

  has_many :addresses, :class_name => "Address"

end

app/controllers/api/v1/merchant_controller.rb
class Api::V1::MerchantController < Api::V1::BaseController

  def index
    merchants = Merchant.all
    response = construct_merchants_list(merchants)
    render_json_success merchants: response
  end

  def show
    merchant = get_merchant
    if merchant.present?
      response = construct_merchant(merchant)
      render_json_success merchants: response
    else
      render_json_failure error: "Please enter email_address or id both"
    end
  end

  private
  def construct_merchants_list(merchants)
    merchants.map do |merchant|
      merchant_hash = {:id=>merchant.id, :email_address=>merchant.email_address, :name=>merchant.name, :type=>merchant.merchant_type, :expire_at=>merchant.expire_at} 
    end
  end

  def get_merchant
    if params[:id].present?
      merchant = Merchant.find(params[:id])
    elsif params[:email_address].present?
      merchant = Merchant.find_by_email_address(params[:email_address])
    end
  end

  def construct_merchant(merchant)
    merchant_info = {:id=>merchant.id, :email_address=>merchant.email_address, :name=>merchant.name, :type=>merchant.merchant_type, :expire_at=>merchant.expire_at} 
    merchant_info[:addresses] = construct_addresses(merchant.addresses)
    merchant_info[:deals] = construct_deals(merchant.deals)
    merchant_info
  end

  def construct_addresses(addresses)
    addresses.map do |addresse|
      {:id=>addresse.id, :addresse=>addresse.merchant_address, :pincode=>addresse.pincode, :latitude=>addresse.latitude, :longitude=>addresse.longitude, :mobile_no=>addresse.mobile_no}
    end
  end

  def construct_deals(deals)
    deals.map do |deal|
      {:id=>deal.id, :title=>deal.title, :description=>deal.description, :price=>deal.price, :discount=>deal.discount, :type=>deal.deal_type, :event_flag=>deal.event_flag, :logo_image=>deal.logo_image}
    end
  end 
end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController
  def index
    @merchants = Merchant.all
  end

  def show
    @merchant = Merchant.find(params[:id])
  end

  def new
    @merchant = Merchant.new
  end

  def create
    @merchant = Merchant.new(params[:merchant])
    if @merchant.save
      flash[:notice] = "Successfully created merchant."
      redirect_to @merchant
    else
      render :action => 'new'
    end
  end

  def edit
    @merchant = Merchant.find(params[:id])
  end

  def update
    @merchant = Merchant.find(params[:id])
    if @merchant.update_attributes(params[:merchant])
      flash[:notice] = "Successfully updated merchant."
      redirect_to merchant_url
    else
      render :action => 'edit'
    end
  end

  def destroy
    @merchant = Merchant.find(params[:id])
    @merchant.destroy
    flash[:notice] = "Successfully destroyed merchant."
    redirect_to merchants_url
  end
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/views/merchants/_form.html.erb
<%= form_for @merchant do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email_address %><br />
    <%= f.text_field :email_address %>
  </p>
  <p>
    <%= f.label :merchant_type %><br />
    <%= f.text_field :merchant_type %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/merchants/edit.html.erb
<% title "Edit Merchant" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @merchant %> |
  <%= link_to "View All", merchants_path %>
</p>

app/views/merchants/index.html.erb
<% title "Merchants" %>

<% for merchant in @merchants %>
  <div class="merchant">
    <h2><%= link_to merchant.name, merchant %></h2>
    Deals: <%= merchant.deals.size %>
  </div>
<% end %>

<p><%= link_to "New Merchant", new_merchant_path %></p>

app/views/merchants/new.html.erb
<% title "New Merchant" %>

<%= render 'form' %>

<p><%= link_to "Back to List", merchants_path %></p>

app/views/merchants/show.html.erb
<% title @merchant.name %>

<div id="deals">
  <% for deal in @merchant.deals %>
    <div class="deal">
      <%= image_tag deal.logo_image_url(:thumb) if deal.logo_image? %>
      <%= image_tag deal.image1_url(:thumb) if deal.image1? %>
      <%= image_tag deal.image2_url(:thumb) if deal.image2? %>
      <%= image_tag deal.image3_url(:thumb) if deal.image3? %>
      <%= image_tag deal.image4_url(:thumb) if deal.image4? %>
      <div class="name"><%= deal.name %></div>
      <div class="actions">
        <%= link_to "edit", edit_deal_path(deal) %> |
        <%= link_to "remove", deal, :confirm => 'Are you sure?', :method => :delete %>
      </div>
    </div>
  <% end %>
  <div class="clear"></div>
</div>
<p>
  <%= link_to "Add a deal", new_deal_path(:merchant_id => @merchant) %> |
  <%= link_to "Add a address", new_address_path(:merchant_id => @merchant) %> |
  <%= link_to "Remove Merchant", @merchant, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View Merchants", merchants_path %>
</p>